###Show 
GET http://localhost:8080/api/test/all
Content-Type: application/json


### Invalid username
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T0127510G",
    "email": "jevontanjinghong@gmail.com",
    "password": "Testing@123"
}


### Invalid email
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T1234567Q",
    "email": "hehexdil.com",
    "password": "estin123"
}


### proper register user / username is taken
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T1234467Q",
    "email": "hehe@gmail.com",
    "password": "Pass1234!"
}

### email taken
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "Z9835241A",
    "email": "hehe@gmail.com",
    "password": "Pass1234!"
}

### Cannot access user resources
GET http://localhost:8080/api/test/user
Content-Type: application/json

{


}


### Login successful
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "B@llsD33p69"
}

### Authentication success
GET http://localhost:8080/api/test/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTIzNDQ2N1EiLCJpYXQiOjE2OTU2MzI5MDgsImV4cCI6MTY5NTcxOTMwOH0.oudhqvlzAj1xN9I8kgglmEzIZ4HGeCNRgX9UnyUdrkg

###
POST http://localhost:8080/api/user/2
Content-Type: application/json

{
    "currentPassword": "Testing@123",
    "newPassword": "B@llsD33p69",
    "confirmPassword": "Testing@123"
}

### Register booking manager
POST http://localhost:8080/api/auth/registerBM
Content-Type: application/json

{
    "username": "T0127510G",
    "email": "zqqzzq@gmail.com",
    "password": "B@llsD33p69"
}



### Login booking manager
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "T0127510G",
    "password": "B@llsD33p69"
}

### Register admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "S8217079D",
    "email": "aqqzzq@gmail.com",
    "password": "Pass1234!",
    "role": ["admin"]
}

### Login admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "Pass1234!"
}

### Add facility
POST http://localhost:8080/api/facilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5ODA0NzU1NywiZXhwIjoxNjk4MTMzOTU3fQ._yOIMTPRMJXf8ploZJtK2cvbB8pR-QNDXxJbTL34jes

{
    "facilityType": "FacilityOne",
    "description": "Default Description"
}

### view facility
GET http://localhost:8080/api/facilities/1
Content-Type: application/json


### Register admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T0127510G",
    "email": "aqqzzq@gmail.com",
    "password": "Pass1234!",
    "role": ["user"]
}


### Change Password
POST http://localhost:8080/api/user/2
Content-Type: application/json

{
    "currentPassword": "Pasggs1234!",
    "newPassword": "B@llsD33p69"
}

### Change Password
POST http://localhost:8080/api/user/2
Content-Type: application/json

{
    "currentPassword": "Pass1234!",
    "newPassword": "B@llsD33p69"
}


### Login successful
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "T0127510G",
    "password": "B@llsD33p69"
}



### make normal user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T0127510G",
    "email": "jevontanjinghong@gmail.com",
    "password": "Testing@123"
}


### Create facility 
POST http://localhost:8080/api/facilities
Content-Type: application/json

{
    "facilityType": "basketball court",
    "description": "indoor court",
    "openTime": "09:00",
    "closingTime": "18:00",
    "creditCost": "50",
    "locationString": "ActiveSG Sengkang" 
}


### Get facis
GET http://localhost:8080/api/facilities
Content-Type: application/json


### Get faci
GET http://localhost:8080/api/facilities/2
Content-Type: application/json


### Get faci dates
GET http://localhost:8080/api/facilities/2/dates
Content-Type: application/json

### Get available timeslots of a date 
GET http://localhost:8080/api/facilities/2/dates/56/timeslots
Content-Type: application/json


### make normal user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "T0127510G",
    "email": "jevontanjinghong@gmail.com",
    "password": "Testing@123"
}


### view facility
GET http://localhost:8080/api/facilities/1
Content-Type: application/json

### make booking
POST http://localhost:8080/api/bookings/makebooking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5ODA0NzU1NywiZXhwIjoxNjk4MTMzOTU3fQ._yOIMTPRMJXf8ploZJtK2cvbB8pR-QNDXxJbTL34jes

{
    "userId":1,
    "facilityId":1,
    "timeBookingMade":"2023-10-23",
    "facilityDate":"2023-10-29",
    "timeSlots":[
          "10:00:00",
          "11:00:00"]
}

### Confirm booking attendance booking
POST http://localhost:8080/api/bookings/confirmbookingattendance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5ODA0NzU1NywiZXhwIjoxNjk4MTMzOTU3fQ._yOIMTPRMJXf8ploZJtK2cvbB8pR-QNDXxJbTL34jes

{
  "bookingId":1,
  "attendanceStatus": 1
}

### Cancel booking
POST http://localhost:8080/api/bookings/cancelbooking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5ODA0NzU1NywiZXhwIjoxNjk4MTMzOTU3fQ._yOIMTPRMJXf8ploZJtK2cvbB8pR-QNDXxJbTL34jes

{
  "bookingId":1
}